Lib32z1 dependency
timche/docker-csgo pull request #10
Opened 2021-02-01 15:14 UTC by horviskoadrianko

I've added lib32z1 because it was missing and mysql database connector deppends on it.

2021-02-01 15:17 UTC, timche requested changes
Thanks for fixing this. I've requested changes.

2021-02-01 15:17 UTC, timche commented on base/Dockerfile
> +    lib32z1 \
Please define the exact version like the other dependencies and install it only on the SourceMod image.

2021-02-01 20:38 UTC, timche reviewed
Can you please rebase to latest master? I'd like to see that the image builds, I've added a GitHub workflow.

2021-02-01 23:39 UTC, horviskoadrianko commented
I tried to add it to sourcemod Dockerfile but it will throw error unable to locate package. I dont really know how to fix this. I will try tomorrow.

2021-02-01 23:45 UTC, timche commented
That's because the [apt cache is removed](https://github.com/timche/docker-csgo/blob/master/base/Dockerfile#L11) in the base image as clean up. You need to run [`apt update`](https://github.com/timche/docker-csgo/blob/master/base/Dockerfile#L3) before you install the dependency.

2021-02-02 07:31 UTC, horviskoadrianko commented
Thank you for helping me.

2021-02-02 10:32 UTC, timche requested changes

2021-02-02 10:32 UTC, timche commented on sourcemod/Dockerfile
> +    && apt-get install lib32z1=1:1.2.11.dfsg-1 \
```suggestion
    && apt-get install -y --no-install-recommends \
    lib32z1=1:1.2.11.dfsg-1 \
```

2021-02-02 10:35 UTC, merged

2021-02-02 10:36 UTC, timche commented
Good job 👍 Thanks for fixing this.